<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-14T17:49:28 EET" name="Default suite" finished-at="2024-07-14T17:49:29 EET" duration-ms="399">
    <groups>
    </groups>
    <test started-at="2024-07-14T17:49:28 EET" name="Default test" finished-at="2024-07-14T17:49:29 EET" duration-ms="399">
      <class name="TestTableEmployees.TestCases">
        <test-method is-config="true" signature="CallwaithDataBase()[pri:0, instance:TestTableEmployees.TestCases@6ca0256d]" started-at="2024-07-14T17:49:28 EET" name="CallwaithDataBase" finished-at="2024-07-14T17:49:29 EET" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CallwaithDataBase -->
        <test-method signature="InsertRowData()[pri:1, instance:TestTableEmployees.TestCases@6ca0256d]" started-at="2024-07-14T17:49:29 EET" name="InsertRowData" finished-at="2024-07-14T17:49:29 EET" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InsertRowData -->
        <test-method signature="UpdateRowData()[pri:2, instance:TestTableEmployees.TestCases@6ca0256d]" started-at="2024-07-14T17:49:29 EET" name="UpdateRowData" finished-at="2024-07-14T17:49:29 EET" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateRowData -->
        <test-method signature="GetRowData()[pri:3, instance:TestTableEmployees.TestCases@6ca0256d]" started-at="2024-07-14T17:49:29 EET" name="GetRowData" finished-at="2024-07-14T17:49:29 EET" duration-ms="5" status="FAIL">
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[Statement.executeUpdate() or Statement.executeLargeUpdate() cannot issue statements that produce result sets.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: Statement.executeUpdate() or Statement.executeLargeUpdate() cannot issue statements that produce result sets.
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1453)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2384)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1410)
at TestTableEmployees.DataTest.callWithDatabase(DataTest.java:29)
at TestTableEmployees.TestCases.GetRowData(TestCases.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetRowData -->
        <test-method signature="DeleteRowData()[pri:4, instance:TestTableEmployees.TestCases@6ca0256d]" started-at="2024-07-14T17:49:29 EET" name="DeleteRowData" finished-at="2024-07-14T17:49:29 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteRowData -->
      </class> <!-- TestTableEmployees.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
